Update GitHub Actions workflow to include deployment to Vercel after tests pass

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,4 +1,4 @@
-name: Run Tests
+name: Run Tests and Deploy a preview to Vercel
 
 on:
   pull_request:
@@ -86,3 +86,45 @@ jobs:
           name: coverage-report
           path: coverage/
           retention-days: 7
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: test
+    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.actor == 'subhash-malireddy'
+
+    env:
+      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
+      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Install Vercel CLI
+        run: npm install --global vercel@latest
+
+      - name: Pull Vercel Environment Information
+        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
+
+      - name: Build Project Artifacts
+        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
+
+      - name: Deploy Project Artifacts to Vercel
+        run: |
+          # Save stdout and stderr to files
+          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} >deployment-url.txt 2>error.txt
+
+          # Check the exit code
+          code=$?
+          if [ $code -eq 0 ]; then
+              # Get the deployment URL from stdout for the next step
+              deploymentUrl=$(cat deployment-url.txt)
+              echo "Deployed to $deploymentUrl"
+              
+              # Set a consistent alias for the deployment
+              vercel alias $deploymentUrl preview-${{ github.repository_owner }}-${{ github.event.repository.name }}.vercel.app --token=${{ secrets.VERCEL_TOKEN }} --scope=${{secrets.VERCEL_TEAM_ID}}
+          else
+              # Handle the error
+              errorMessage=$(cat error.txt)
+              echo "There was an error: $errorMessage"
+              exit 1
+          fi
